In [49]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [7]:
X = tf.random.uniform((100,1))
y = (X + 5) * 3

In [9]:

X.shape, y.shape

(TensorShape([100, 1]), TensorShape([100, 1]))

In [10]:
tf.shape(X)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([100,   1], dtype=int32)>

In [12]:
model = tf.keras.Sequential([
    tf.keras.layers.Input(name="InputLayer",shape=[1]),
    tf.keras.layers.Dense(100,name="H_Layer1"),
    tf.keras.layers.Dense(50, name="H_Layer2"),
    tf.keras.layers.Dense(10, name="H_Layer3"),
    tf.keras.layers.Dense(1, name="Output_Layer")])

In [13]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ H_Layer1 (Dense)                │ (None, 100)            │           200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ H_Layer2 (Dense)                │ (None, 50)             │         5,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ H_Layer3 (Dense)                │ (None, 10)             │           510 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_Layer (Dense)            │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,771 (22.54 KB)

 Trainable params: 5,771 (22.54 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.compile(loss="MSE", optimizer="adam")

In [26]:
model.fit(X,y,epochs=4,batch_size=13)

Epoch 1/4
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1240 
Epoch 2/4
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1021 
Epoch 3/4
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0643 
Epoch 4/4
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0537 


In [32]:
model.predict(np.array([[9]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


array([[47.770454]], dtype=float32)

In [37]:
(np.array([9])+ 5)* 3

array([42])

In [39]:
x_test = tf.random.uniform((10,1))

In [54]:
y_pred = model.predict(x_test)
y_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[15.043068],
       [16.437626],
       [18.094053],
       [18.043148],
       [15.747721],
       [17.434696],
       [15.971221],
       [16.553654],
       [15.211063],
       [17.219545]], dtype=float32)

In [59]:
y_test =[]
for i in x_test:
    y = (i+5)*3
    y_test.append(float(y))
y_test


[15.335712432861328,
 16.471914291381836,
 17.82147216796875,
 17.779996871948242,
 15.909822463989258,
 17.28426742553711,
 16.0919189453125,
 16.566448211669922,
 15.472586631774902,
 17.108976364135742]

In [64]:
Loss = abs(y_pred - y_test)
y_pred = y_pred.flatten()
DF = pd.DataFrame({
    'y test': y_test,
    'y pred': y_pred,"Loss":Loss
})
DF

y test     y pred      Loss
0  15.335712  15.043068  0.292645
1  16.471914  16.437626  0.034288
2  17.821472  18.094053  0.272581
3  17.779997  18.043148  0.263151
4  15.909822  15.747721  0.162102
5  17.284267  17.434696  0.150429
6  16.091919  15.971221  0.120698
7  16.566448  16.553654  0.012794
8  15.472587  15.211063  0.261523
9  17.108976  17.219545  0.110569